# Generated by Django 3.1.7 on 2021-04-17 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
                ('rank', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(help_text='please provide relevant topic!', max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
                ('label', models.CharField(choices=[('hot', 'hot'), ('new', 'new'), ('most_viewed', 'most_viewed'), ('', 'default')], max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profession', models.CharField(help_text='you can specify your permanent job!', max_length=100)),
                ('review', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=1, help_text='enter rating between 1-5!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='passive', max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1, help_text='enter rating between 1-5!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('checkout', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
