# Generated by Django 3.1.7 on 2021-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210417_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereview',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
