# Generated by Django 3.1.7 on 2021-04-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sitereview_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitereview',
            old_name='title',
            new_name='name',
        ),
    ]
