# Generated by Django 3.1.7 on 2021-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210417_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereview',
            name='desc',
            field=models.TextField(blank=True, default=None),
        ),
    ]
