# Generated by Django 3.1.7 on 2021-04-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sitereview_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitereview',
            name='desc',
        ),
    ]
