# Generated by Django 3.1.7 on 2021-04-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210417_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
