# Generated by Django 3.1.7 on 2021-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210417_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100),
        ),
    ]
