# Generated by Django 3.1.7 on 2021-04-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210418_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200)),
                ('net_total', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('checkout', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.cart')),
            ],
        ),
    ]
