# Generated by Django 3.1.7 on 2021-04-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210418_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttotal',
            name='slug',
        ),
    ]
