# Generated by Django 3.1.7 on 2021-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_carttotal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='slug',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
