# Generated by Django 3.1.7 on 2021-04-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_carttotal_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='myapp.cart'),
        ),
    ]
