# Generated by Django 3.1.7 on 2021-04-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_carttotal_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttotal',
            name='slug',
        ),
    ]
