# Generated by Django 3.1.7 on 2021-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210418_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttotal',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
        ),
    ]
