# Generated by Django 3.1.7 on 2021-04-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210418_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
