# Generated by Django 3.1.7 on 2021-04-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_carttotal_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttotal',
            name='products',
        ),
    ]
