# Generated by Django 3.1.7 on 2021-04-21 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20210419_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_add', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('checkout', models.BooleanField(default=True)),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
