# Generated by Django 3.1.7 on 2021-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
