# Generated by Django 3.1.7 on 2021-04-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_checkout_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
