# Generated by Django 3.1.7 on 2021-04-22 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20210422_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200)),
                ('net_total', models.IntegerField(default=0)),
                ('slug', models.CharField(default=None, max_length=100, unique=True)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('checkout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_add', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('checkout', models.BooleanField(default=True)),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='carttotal',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
        ),
    ]
