# Generated by Django 3.1.7 on 2021-04-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_checkout_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='username',
        ),
    ]
