# Generated by Django 3.1.7 on 2021-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_checkout_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='zip_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
