# Generated by Django 3.1.7 on 2021-04-22 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_checkout_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_add', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('zip_code', models.CharField(default=None, max_length=20)),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
