# Generated by Django 3.1.7 on 2021-04-24 16:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_checkoutcart_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutcart',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True),
        ),
    ]
