# Generated by Django 3.1.7 on 2021-04-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_checkoutcart_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='country',
        ),
    ]
