# Generated by Django 3.1.7 on 2021-04-26 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_auto_20210425_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='date_checked',
        ),
        migrations.AddField(
            model_name='carttotal',
            name='date_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
