# Generated by Django 3.1.7 on 2021-04-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20210426_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='products',
        ),
    ]
