# Generated by Django 3.1.7 on 2021-04-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_remove_checkoutcart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttotal',
            name='cart',
        ),
    ]
