# Generated by Django 3.1.7 on 2021-04-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_remove_carttotal_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
        ),
    ]
